// handles the page where the user can view the schedule they have made. Will not show a schedule if there are conflicts.
import { useEffect, useState } from 'react'
import { Link } from "react-router-dom"
import FullCalendar from '@fullcalendar/react'
import timeGridPlugin from '@fullcalendar/timegrid'
import cookies from 'react-cookies'

const dayMapping = {
    'M': 1,
    'T': 2,
    'W': 3,
    'R': 4,
    'F': 5,
    'S': 6,
    'U': 0
};

const Schedule = () => {
    const [hasConflict, setHasConflict] = useState(false);
    const [courses, setCourses] = useState([]);

    const fetchScheduleData = () => {
        const selectedCourses = cookies.load('selectedCourses') || [];
        if (selectedCourses.length > 0) {
            fetch(`http://localhost:8080/api/isConflict?courses=${selectedCourses.join(',')}`)
                .then(response => response.json())
                .then(data => {
                    setHasConflict(data);
                    if (!data) {
                        fetch(`http://localhost:8080/api/coursesInfo?courses=${selectedCourses.join(',')}`)
                        .then(response => response.json())
                        .then(data => {
                            setCourses(data);
                            console.log(data);
                        })
                        .catch(error => console.error('Error fetching data:', error));
                    }
                })
                .catch(error => console.error('Error fetching data:', error));
        }
    };

    useEffect(() => {
        fetchScheduleData();
    }, []);

    // mostly generated by AI
    const handleDownload = () => {
        const filename = window.prompt("Enter the filename", "your_filename.txt");
        if (!filename) {
            return; // If the user cancels the prompt, do nothing
        }
        const coursesData = courses.map(course => `${course.department}${course.courseCode}${course.section}${course.semester}`).join(',');

        fetch(`http://localhost:8080/api/download/${filename}?courses=${encodeURIComponent(coursesData)}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        .then(response => {
            if (response.ok) {
                return response.blob();
            }
            throw new Error('Network response was not ok.');
        })
        .then(blob => {
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            a.remove();
            window.URL.revokeObjectURL(url);
        })
        .catch(error => console.error('Error downloading file:', error));
    };

    // mostly generated by AI
    const handleFileLoad = (event) => {
        const file = event.target.files[0];
        if (file) {
            const formData = new FormData();
            formData.append('file', file);

            fetch(`http://localhost:8080/api/upload`, {
                method: 'POST',
                body: formData
            })
            .then(response => {
                if (response.ok) {
                    return response.json(); // Read the response as JSON
                }
                throw new Error('Network response was not ok.');
            })
            .then(data => {
                const courseIds = data.map(course => `${course.department}${course.courseCode}${course.section}${course.semester}`);
                cookies.save('selectedCourses', courseIds, { path: '/' });
                fetchScheduleData();
                alert('Schedule loaded successfully!');
            })
            .catch(error => console.error('Error uploading file:', error));
        }
    };

    if (hasConflict) {
        return (
            <div>
                <h2>There is a conflict in your schedule</h2>
                <div className="button-container">
                    <span> Load Schedule: </span>
                    <input type="file" onChange={handleFileLoad} className='scheduleButton button'/>
                </div>
            </div>
        );
    }

    return (
        <div>
            <div className="button-container">
                <span> Load Schedule: </span>
                <input type="file" onChange={handleFileLoad} className='scheduleButton button'/>
                <button onClick={handleDownload} className="scheduleButton button">Save As</button>
            </div>
        <FullCalendar
            height='auto'
            expandRows={true}
            plugins={[timeGridPlugin]}
            initialView="timeGridWeek"
            showNonCurrentDates={false}
            dayHeaderFormat = {{
                weekday: 'long',
                month: undefined,
                day: undefined
            }}
            weekends={false}
            allDaySlot={false}
            headerToolbar={false}
            events={courses.flatMap(course =>
                Object.entries(course.times).map(([day, time]) => ({
                    eventDisplay: 'block',
                    displayEventTime: false,
                    title: `${course.department}${course.courseCode}#${course.section}`,
                    daysOfWeek: [dayMapping[day]],
                    startTime: time[0],
                    endTime: time[1],
                    startRecur: '2023-01-01',
                    endRecur: '2027-12-31'
                }))
            )}
            eventColor='#333'
            slotMinTime='06:00:00'
            slotMaxTime='22:00:00'
        />
    </div>
    );
}

export default Schedule;